In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
# Read the CSV file
df = pd.read_csv("../data/homework3bus.csv")

# Display the dataframe
df

ModuleNotFoundError: No module named 'matplotlib'

### Create Price Dataframes for specific dates

In [11]:
price_df = pd.read_csv(f"../data/0096WD_7_N001_LMP_12months.csv")

# Sort dataframe by date times INTERVALSTARTTIME_GMT
price_df = price_df.sort_values(by="INTERVALSTARTTIME_GMT")


price_df

,INTERVALSTARTTIME_GMT,INTERVALENDTIME_GMT,OPR_DT,OPR_HR,OPR_INTERVAL,NODE_ID_XML,NODE_ID,NODE,MARKET_RUN_ID,LMP_TYPE,XML_DATA_ITEM,PNODE_RESMRID,GRP_TYPE,POS,MW,GROUP
0,2025-01-01 00:00:00+00:00,2025-01-01 01:00:00+00:00,2024-12-31,17,0,0096WD_7_N001,0096WD_7_N001,0096WD_7_N001,DAM,LMP,LMP_PRC,0096WD_7_N001,ALL,1,51.50206,1
1,2025-01-01 01:00:00+00:00,2025-01-01 02:00:00+00:00,2024-12-31,18,0,0096WD_7_N001,0096WD_7_N001,0096WD_7_N001,DAM,LMP,LMP_PRC,0096WD_7_N001,ALL,1,52.66897,1
2,2025-01-01 02:00:00+00:00,2025-01-01 03:00:00+00:00,2024-12-31,19,0,0096WD_7_N001,0096WD_7_N001,0096WD_7_N001,DAM,LMP,LMP_PRC,0096WD_7_N001,ALL,1,51.19425,1
3,2025-01-01 03:00:00+00:00,2025-01-01 04:00:00+00:00,2024-12-31,20,0,0096WD_7_N001,0096WD_7_N001,0096WD_7_N001,DAM,LMP,LMP_PRC,0096WD_7_N001,ALL,1,51.23666,1
4,2025-01-01 04:00:00+00:00,2025-01-01 05:00:00+00:00,2024-12-31,21,0,0096WD_7_N001,0096WD_7_N001,0096WD_7_N001,DAM,LMP,LMP_PRC,0096WD_7_N001,ALL,1,51.32875,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2025-12-31 19:00:00+00:00,2025-12-31 20:00:00+00:00,2025-12-31,12,0,0096WD_7_N001,0096WD_7_N001,0096WD_7_N001,DAM,LMP,LMP_PRC,0096WD_7_N001,ALL,1,44.92084,6
8756,2025-12-31 20:00:00+00:00,2025-12-31 21:00:00+00:00,2025-12-31,13,0,0096WD_7_N001,0096WD_7_N001,0096WD_7_N001,DAM,LMP,LMP_PRC,0096WD_7_N001,ALL,1,44.33853,6
8757,2025-12-31 21:00:00+00:00,2025-12-31 22:00:00+00:00,2025-12-31,14,0,0096WD_7_N001,0096WD_7_N001,0096WD_7_N001,DAM,LMP,LMP_PRC,0096WD_7_N001,ALL,1,44.30966,6
8758,2025-12-31 22:00:00+00:00,2025-12-31 23:00:00+00:00,2025-12-31,15,0,0096WD_7_N001,0096WD_7_N001,0096WD_7_N001,DAM,LMP,LMP_PRC,0096WD_7_N001,ALL,1,43.52434,6
8759,2025-12-31 23:00:00+00:00,2026-01-01 00:00:00+00:00,2025-12-31,16,0,0096WD_7_N001,0096WD_7_N001,0096WD_7_N001,DAM,LMP,LMP_PRC,0096WD_7_N001,ALL,1,43.37472,6

In [ ]:
# Create a plot for "INTERVALSTARTTIME_GMT" vs MW between 2025-04-10 and 2025-04-13

def plotInterval(df, startDt, endDt):
    # Filter the dataframe for the specified date range
    mask = (df['INTERVALSTARTTIME_GMT'] >= startDt) & (df['INTERVALSTARTTIME_GMT'] <= endDt)
    filtered_df = df.loc[mask]

    # Plotting
    plt.figure(figsize=(12, 6))
    plt.plot(filtered_df['INTERVALSTARTTIME_GMT'], filtered_df['MW'], marker='o')
    plt.title('MW vs INTERVALSTARTTIME_GMT')
    plt.xlabel('INTERVALSTARTTIME_GMT')
    plt.ylabel('MW')
    plt.xticks(rotation=45)
    plt.grid()
    plt.tight_layout()
    plt.show()

_IncompleteInputError: incomplete input (406410470.py, line 3)

In [5]:
from datetime import date


def import_clean_save(orig_filename, new_filename):
    df = pd.read_csv(f"../data/{orig_filename}.csv")
    # Only keep the columns OPR_DT, OPR_HR, and MW
    df = df[["OPR_DT", "OPR_HR", "MW"]]

    # rename the columns from "MW" to "$/MW"
    df = df.rename(columns={"MW": "$/MW"})

    display(df)    

    # Save the filtered dataframe to a new CSV file in data folder with the specified filename
    filepath = f"../data/{new_filename}"
    df.to_csv(filepath, index=False)

import_clean_save("bad_0096WD_7_N001_fall_2025_10_10", "pricedf_0096WD_7_N001_fall_2025_10_10.csv")
import_clean_save("bad_0096WD_7_N001_spring_2025_04_10", "pricedf_0096WD_7_N001_spring_2025_04_10.csv")
import_clean_save("bad_0096WD_7_N001_summer_2025_07_10", "pricedf_0096WD_7_N001_summer_2025_07_10.csv")
import_clean_save("bad_0096WD_7_N001_winter_2025_01_10", "pricedf_0096WD_7_N001_winter_2025_01_10.csv")

        OPR_DT  OPR_HR      $/MW
0   2025-10-10       1  49.29410
1   2025-10-10      10  30.87718
2   2025-10-10      11  34.62440
3   2025-10-10      12  33.65542
4   2025-10-10      13  33.12107
5   2025-10-10      14  33.10358
6   2025-10-10      15  34.50378
7   2025-10-10      16  35.75029
8   2025-10-10      17  43.05643
9   2025-10-10      18  51.93690
10  2025-10-10      19  53.71969
11  2025-10-10       2  49.32583
12  2025-10-10      20  53.39004
13  2025-10-10      21  51.55561
14  2025-10-10      22  50.78716
15  2025-10-10      23  51.38565
16  2025-10-10      24  49.13029
17  2025-10-10       3  47.16058
18  2025-10-10       4  45.52610
19  2025-10-10       5  45.12169
20  2025-10-10       6  46.47834
21  2025-10-10       7  54.11392
22  2025-10-10       8  52.29877
23  2025-10-10       9  39.92995

        OPR_DT  OPR_HR      $/MW
0   2025-04-10       1  40.58558
1   2025-04-10      10  -5.95592
2   2025-04-10      11  -5.98615
3   2025-04-10      12  -6.73350
4   2025-04-10      13  -6.96041
5   2025-04-10      14  -7.67232
6   2025-04-10      15  -7.40127
7   2025-04-10      16  -4.26594
8   2025-04-10      17   2.13313
9   2025-04-10      18  22.65935
10  2025-04-10      19  43.59506
11  2025-04-10       2  40.09454
12  2025-04-10      20  47.36342
13  2025-04-10      21  44.83490
14  2025-04-10      22  42.50052
15  2025-04-10      23  41.97505
16  2025-04-10      24  38.77458
17  2025-04-10       3  36.11954
18  2025-04-10       4  34.84595
19  2025-04-10       5  36.45646
20  2025-04-10       6  41.48765
21  2025-04-10       7  49.13702
22  2025-04-10       8  33.06252
23  2025-04-10       9  -1.60682

        OPR_DT  OPR_HR      $/MW
0   2025-07-10       1  41.95490
1   2025-07-10      10  25.99782
2   2025-07-10      11  29.71807
3   2025-07-10      12  30.03076
4   2025-07-10      13  29.08538
5   2025-07-10      14  29.46032
6   2025-07-10      15  32.66149
7   2025-07-10      16  36.96077
8   2025-07-10      17  40.61177
9   2025-07-10      18  49.21868
10  2025-07-10      19  53.71628
11  2025-07-10       2  41.36804
12  2025-07-10      20  75.19591
13  2025-07-10      21  67.93754
14  2025-07-10      22  58.18868
15  2025-07-10      23  47.58371
16  2025-07-10      24  46.15824
17  2025-07-10       3  42.96804
18  2025-07-10       4  40.91897
19  2025-07-10       5  40.08064
20  2025-07-10       6  41.94995
21  2025-07-10       7  39.92837
22  2025-07-10       8  31.31394
23  2025-07-10       9  25.69168

        OPR_DT  OPR_HR      $/MW
0   2025-01-10       1  44.02247
1   2025-01-10      10  20.14818
2   2025-01-10      11  18.71779
3   2025-01-10      12  17.51152
4   2025-01-10      13  16.36023
5   2025-01-10      14  13.80814
6   2025-01-10      15  15.27612
7   2025-01-10      16  25.82143
8   2025-01-10      17  46.41052
9   2025-01-10      18  49.76798
10  2025-01-10      19  48.32014
11  2025-01-10       2  43.58637
12  2025-01-10      20  47.07377
13  2025-01-10      21  46.58034
14  2025-01-10      22  46.54286
15  2025-01-10      23  45.85853
16  2025-01-10      24  44.74139
17  2025-01-10       3  43.61065
18  2025-01-10       4  43.78152
19  2025-01-10       5  43.85652
20  2025-01-10       6  50.77697
21  2025-01-10       7  56.36985
22  2025-01-10       8  52.07950
23  2025-01-10       9  34.26323

In [ ]:
# def filter_by_starttime_day_and_save(df, date, filename):
#     # Combing hour from OP
    
#     # Only keep the columns INTERVALSTARTTIME_GMT and MW
#     df = df[["INTERVALSTARTTIME_GMT", "MW"]]

#     # rename the columns from "INTERVALSTARTTIME_GMT" to "StartTime_GMT" and "MW" to "$/MW"
#     df = df.rename(columns={"INTERVALSTARTTIME_GMT": "StartTime_GMT", "MW": "$/MW"})

#     # Convert INTERVALSTARTTIME_GMT to datetime
#     df["StartTime_GMT"] = pd.to_datetime(df["StartTime_GMT"])

#     # Filter the dataframe for the specified date
#     filtered_df = df[
#         df["StartTime_GMT"].dt.date == pd.to_datetime(date).date()
#     ].reset_index(drop=True)

#     display(filtered_df)

#     # Save the filtered dataframe to a new CSV file in data folder with the specified filename
#     filepath = f"../data/{filename}"
#     filtered_df.to_csv(filepath, index=False)

In [ ]:
# def filter_by_day_and_save(df, date, filename):
#     # Only keep the columns INTERVALSTARTTIME_GMT and MW
#     df = df[["INTERVALSTARTTIME_GMT", "MW"]]

#     # rename the columns from "INTERVALSTARTTIME_GMT" to "StartTime_GMT" and "MW" to "$/MW"
#     df = df.rename(columns={"INTERVALSTARTTIME_GMT": "StartTime_GMT", "MW": "$/MW"})

    

#     # Convert INTERVALSTARTTIME_GMT to datetime
#     df["StartTime_GMT"] = pd.to_datetime(df["StartTime_GMT"])

#     # Filter the dataframe for the specified date
#     filtered_df = df[df["StartTime_GMT"].dt.date == pd.to_datetime(date).date()].reset_index(drop=True)
    
#     display(filtered_df)
    
#     # Save the filtered dataframe to a new CSV file in data folder with the specified filename
#     filepath = f"../data/{filename}"
#     filtered_df.to_csv(filepath, index=False)

# filter_by_day_and_save(price_df, "2025-04-10", "price_df_0096WD_7_N001_2025-04-10.csv")
# filter_by_day_and_save(price_df, "2025-04-10", "price_df_0096WD_7_N001_2025-04-10.csv")
# filter_by_day_and_save(price_df, "2025-04-10", "price_df_0096WD_7_N001_2025-04-10.csv")
# filter_by_day_and_save(price_df, "2025-04-10", "price_df_0096WD_7_N001_2025-04-10.csv")

               StartTime_GMT      $/MW
0  2025-04-10 00:00:00+00:00  18.39588
1  2025-04-10 01:00:00+00:00  48.76914
2  2025-04-10 02:00:00+00:00  54.68878
3  2025-04-10 03:00:00+00:00  50.35215
4  2025-04-10 04:00:00+00:00  48.64582
5  2025-04-10 05:00:00+00:00  46.69302
6  2025-04-10 06:00:00+00:00  43.54821
7  2025-04-10 07:00:00+00:00  40.58558
8  2025-04-10 08:00:00+00:00  40.09454
9  2025-04-10 09:00:00+00:00  36.11954
10 2025-04-10 10:00:00+00:00  34.84595
11 2025-04-10 11:00:00+00:00  36.45646
12 2025-04-10 12:00:00+00:00  41.48765
13 2025-04-10 13:00:00+00:00  49.13702
14 2025-04-10 14:00:00+00:00  33.06252
15 2025-04-10 15:00:00+00:00  -1.60682
16 2025-04-10 16:00:00+00:00  -5.95592
17 2025-04-10 17:00:00+00:00  -5.98615
18 2025-04-10 18:00:00+00:00  -6.73350
19 2025-04-10 19:00:00+00:00  -6.96041
20 2025-04-10 20:00:00+00:00  -7.67232
21 2025-04-10 21:00:00+00:00  -7.40127
22 2025-04-10 22:00:00+00:00  -4.26594
23 2025-04-10 23:00:00+00:00   2.13313